file_ob=open("newf.txt","w")
file_ob.write("File is a collection of related data.\n fa\n")
print("file created")
file_ob=open("newf.txt","r")
text1=file_ob.readline()
print(text1)
file_ob.close()
file_ob=open("newf.txt","w")
file_ob.write("It has following operations. 1\nREAD.2.\nWRITE\n3.COSE")
text2=file_ob.readlines()
print(text2)
